variables:
  GIT_STRATEGY: fetch

backup:
  image: lfaoro/flares
  stage: build
  retry: 2
  script: |
    # Create a token at https://dash.cloudflare.com/profile/api-tokens
    # Required scope: Zone.DNS -> Read

    flares export --all
  artifacts:
    untracked: true
    expire_in: 4 weeks
    name: "dns-backup-${CI_PIPELINE_ID}"
    paths:
      - ./*
